### ISSUE TITLE
Setting key within object.

### ISSUE THREAD

**Issue by deweyaccounts** [de-luca/electron-json-config#1]
How would one go about setting a value within an object? Would we need to recreate the whole object and then just set that as a key? I have an object within my config called "network" that looks like this:

```
{
    'apikey' : '0000-1111-3333-4444',
    'network' : {
           'mac_address' : '00:11:22:33:44:55',
           'ip_address' : '192.168.1.50'
    },
    'username' : 'user123'
}
```
I cannot set it like this : `config.set('network.ip_address', '192.168.1.55');`

but I can do this :

```
var networktemp = config.get('network');
networktemp.ip_address = '192.168.1.50';
config.set('network' networktemp);
```

I guess I just answered my own question. I really appreciate this module! It definitely abstracts aways the sometimes convoluted work of dealing with json files using node's (fs) function.

**Comment by deweyaccounts** [comment]
I don't really need a better way to do this. I just wanted to show what one could easily do to modify an object stored in an Electron application using **electron-json-config** in case anyone were to be confused by this. In order to retrieve a specific key within an object, I would do this :

```
var networktemp = config.get('network');
console.log(networktemp.ip_address);
```

Pretty simple!

**Comment by de-luca** [comment]
In fact, deep setting key has not been intended in the first version.
But that's definitely something that could be useful.
