### ISSUE TITLE
can there be a bulk version of set?

### ISSUE THREAD

**Issue by hkuclion** [de-luca/electron-json-config#10]
I have a setting of about 20 items,
when user commit the setting form, I have to set data item by item,
and this will result in writing the file 20 times, which is unnecessary.

so if there is another `set` function like `setBulk` which accept an object and iterate over it, set entries and then write result to file, 
or give a option to original `set`, which can prevent writing file to disk, and expose `sync` function for writing file,
will somehow solve this problem

and delete may have the same behavior

**Comment by de-luca** [comment]
You could set the whole objet in one `set` but that may not match your use case.
I'll see what I can do to limit write operations.

**Comment by hkuclion** [comment]
thanks for the update
