### ISSUE TITLE
Types missing?

### ISSUE THREAD

**Issue by system32uwu** [de-luca/electron-json-config#220]
![image](https://user-images.githubusercontent.com/29718978/115127316-f430e080-9fab-11eb-88c0-4a9b40280b70.png)

**Comment by de-luca** [comment]
Are you using version 2.0.0-beta? 
Typescript is part of the 2.0.0 rewrite of the lib.

**Comment by system32uwu** [comment]
I installed it using `yarn add electron-json-config`, do I need to specify @2.0.0-beta?

**Comment by de-luca** [comment]
As of right now you'll need to specify @2.0.0-beta in order to get the typescript rewrite.
I'll make it clearer in the readme.

**Comment by system32uwu** [comment]
Ok that's it then, feel free to close when you update the readme

**Comment by de-luca** [comment]
Readme has been updated on e77a06f with beta install commands.
Feel free to open a new issue if you have any trouble.
