### ISSUE TITLE
Read Config File Initialization

### ISSUE THREAD

**Issue by dwampler35** [de-luca/electron-json-config#23]
Currently, the config file is loaded after receiving the electron 'ready' signal.  If Electron was already loaded, you will never receive that signal, so the config file will not be read.

I couldnt figure out how to run or pass the integration tests you have, so I'll just paste my diff here.  It is simple enough:

```diff
--- a/src/index.js
+++ b/src/index.js
@@ -7,14 +7,21 @@ const file = (electron.app || electron.remote.app).getPath('userData')+'/config.
 
 let config = {};
 
-
-(electron.app || electron.remote.app).on('ready', () => {
+let readConfig = () => {
   if(!u.exists(file)) {
     fs.writeFileSync(file, '{}');
   }
-
   config = JSON.parse(fs.readFileSync(file));
-});
+}; 
+
+if (electron.remote.app && electron.remote.app.isReady()) {
+  readConfig();
+}
+else {
+  (electron.app || electron.remote.app).on('ready', () => {
+    readConfig();
+  });
+}

**Comment by crivotz** [comment]
Thanks @dwampler35. Works like a charm

**Comment by dwampler35** [comment]
Can a maintainer of this repo please commit this change?  I'd like to use the npm version instead of my private version.  

Thanks.

**Comment by dwampler35** [comment]
Looks good.

Much appreciated.
