### ISSUE TITLE
cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by bgrayburn** [de-luca/electron-json-config#25]
in src/index line 19, the second half of the or conditional reads `electron.remote.app && electron.remote.app.isReady())` this throws an error on the node js end of things when the app isn't ready because electron.remote is undefined. Solution is to change to `electron.remote && electron.remote.app && electron.remote.app.isReady())`. Shall I submit a pull request for this?

**Comment by bgrayburn** [comment]
went ahead and fixed it in a fork so submitted a pull request #26

**Comment by de-luca** [comment]
Thank you for your report and your pull request that helps a lot.  
I'll get around it tonight.

**Comment by de-luca** [comment]
This is released under 1.5.3
