### ISSUE TITLE
cannot find module ...config.json

### ISSUE THREAD

**Issue by bgrayburn** [de-luca/electron-json-config#5]
after using with webpack/babel to build I'm getting the following error when running an electron app with this lib:

`App threw an error when running [Error: Cannot find module '/Users/bgrayburn/Library/Application Support/NewSapienceModelEditor/config.json'.]`

my understanding is this is coming from the require(file) line in the index.js of electron-json-config because such a config file module isn't loaded by webpack. I don't want to load the config file with webpack, but I do want to be able to use this lib with webpack.

My suggestion would be to use fs.readSync instead of require in the lib.  How does this sound?

**Comment by de-luca** [comment]
That sounds good.
I'll see what I can do.

**Comment by bgrayburn** [comment]
made the change locally and it worked. Here's the change:
`var config = JSON.parse(fs.readFileSync(file));
//var config = require(file);`

on line 12 of index.js

I'd be happy to submit a pull request, cannot think of a good test for this

**Comment by de-luca** [comment]
Thanks for your interest!
Don't worry the pull request is already in progress.
