### ISSUE TITLE
Accessing and updating in the main window

### ISSUE THREAD

**Issue by jfreak53** [de-luca/electron-json-config#56]
Is there anyway to access the config data and consequently update it from the main Javascript window?

**Comment by de-luca** [comment]
It is possible to access data from either processes (renderer and main).
However updating data from one process to get it in the other one would not be possible (hazardous) in some case.

Do you mind detailing a bit more your issue so I could look into it more in depth?

**Comment by de-luca** [comment]
I'll close this issue for now.
Feel free to reopen or create a new one if you need any help.
